AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Network Template: template that include RDS contents with standard design.

Parameters:
  RDSInstanceType:
    Type: String
    Description: Select RDS Instance Type
    AllowedValues: [db.t2.micro, db.t2.small, db.t2.medium, db.t2.large,
      db.t3.micro, db.t3.small, db.t3.medium, db.t3.large,]
    Default: db.t2.micro

  DBAllocatedStorage:
    Description: 'The allocated storage size, specified in GB (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: Number
    Default: 20
    MinValue: 5
    MaxValue: 30
  
  EngineVersion:
    Description: 'MySQL version.'
    Type: String
    Default: '5.7.21'
    AllowedValues: ['8.0.15', '5.7.25', '5.7.21', '5.6.41', '5.5.61']

  RDSDBName:
    Type: String
    Description: Your DB name
    Default: 'ecloudformation'

  RDSMasterUserName:
    Type: String
    Description: Your DB username
    Default: 'admin'
  RDSMasterPassword:
    Type: String
    Description: Your DB password
    NoEcho: true
    Default: ''
  



Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: WeAreGroupG
      SubnetIds:
      #need to !sub
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet2
  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AllowMajorVersionUpgrade: false
      DBInstanceClass: !Ref RDSInstanceType
      DBName: !Ref RDSDBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref RDSMasterUserName
      MasterUserPassword: !Ref RDSMasterPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups: 
      #need to !sub
      - Fn::ImportValue: !Sub ${NetworkStackName}-DBSG

Outputs:
  RDSEndpoint:
    Description: 'The connection endpoint for the database.'
    Value: !GetAtt 'DBInstance.Endpoint.Address'
    Export:
      Name: !Sub '${AWS::StackName}-RDSEndpoint'

  DBname: 
    Description: 'The name for the database.'
    Value: !Ref RDSDBName
    Export:
      Name: !Sub '${AWS::StackName}-RDSDBname'

  DBusername: 
    Description: 'The username for the database.'
    Value: !Ref RDSMasterUserName
    Export:
      Name: !Sub '${AWS::StackName}-RDSDBusername'

  DBpassword: 
    Description: 'The password for the database.'
    Value: !Ref RDSMasterPassword
    Export:
      Name: !Sub '${AWS::StackName}-RDSDBpassword'
  

  