AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template creates EIP NAT IGWAttach'
Properties:

Resources:
  VPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref {InternetGateway}
      VPCId: !Ref {VPC}


      

